export { default as Buttons } from "./Button";
export { default as CourseCard } from "./CourseCard";
export { default as HeadWrap } from "./HeadWrap";
export { default as SwiperSlides } from "./SwiperSlides";
export { default as TrainCard } from "./TrainCard";
export { default as ContactForm } from "./ContactForm";
export { default as Faq } from "./Faq";
export { default as ToolCard } from "./ToolCard";
export { default as KeyCards } from "./KeyCards";
